### ISSUE TITLE
Unable to log in to the wiki

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/roadkill-vocadb-auth#2]
**Website**
VocaDB wiki

https://wiki.vocadb.net/User/Login

Message "Sorry, an error occurred while processing your request. " appears when trying to log in to the VocaDB wiki (username + access key).

**Comment by riipah** [comment]
You're not supposed to log in to the wiki. It's supposed to use the authentication from the main website. You log in to VocaDB and it logs you in to the wiki. This is possible because they are both under *.vocadb.net domain.

I mean, that's how it used to work. Now that the main website is .NET Core, the authentication may not work the same way. I recall there was still some way to reuse the authentication cookie between .NET Core and Framework, but it may need tweaks on the wiki site. It might also be possible to get that authentication page on the wiki working, so you'd just use that.
